"""Data master barang untuk kedua paket kejuruan.

Setiap item: (nama, spesifikasi, volume, satuan, harga_satuan)
Subtotal/total dihitung otomatis oleh generator (volume * harga_satuan).
"""

# ==========================================================================
# PAKET 1 : PERACIKAN MINUMAN KOPI (BARISTA)  - 180 JP
# ==========================================================================
KOPI = {
    "kejuruan": "Barista",
    "bidang": "Peracikan Minuman Kopi",
    "judul": "Peracikan Minuman Kopi",
    "jam": "180 JP",
    "items": [
        ("Kertas HVS", "Ukuran A4 75 Gsm, Merk Paper One/Setara", 2, "Rim", 50000),
        ("Kertas HVS", "Ukuran F4 75 Gsm, Merk Paper One/Setara", 1, "Rim", 65000),
        ("Highlighter", "Pulpen Stabilo, Ukuran kecil, Merk Joyko/Setara", 16, "Buah", 15000),
        ("Isi Stapler", "Ukuran No. 10, Merk Joyko/Setara", 5, "Buah", 5000),
        ("Spidol", "Whiteboard Marker, Merk Snowman/Setara", 10, "Buah", 12000),
        ("Sticky Notes", "Bentuk Persegi Empat, Merk Post-it/Setara", 1, "Buah", 15000),
        ("Shot Glass", "Ukuran 30-40 ml, Bahan Kaca", 4, "Rim", 35000),
        ("Baterai AAA", "Isi 6, Merk Alkaline", 2, "Rim", 8000),
        ("Baterai AA", "Isi 6, Merk Alkaline", 2, "Botol", 7000),
        ("Pewarna Makanan", "Ukuran 1 Liter, Warna Hitam dan Merah, Merk Koepoe Koepoe/Setara", 2, "Botol", 110000),
        ("Galon", "Isi 19 Liter, Merk Aqua", 25, "Botol", 6000),
        ("Grouphead Brush", "Kualitas Baik", 6, "Botol", 65000),
        ("Apron", "Warna gelap", 2, "Buah", 125000),
        ("Espresso Machine Cleaner", "Isi 120 Tablet, Merk Puro/Setara", 5, "Buah", 320000),
        ("Sabun Pencuci Piring", "Ukuran 5 Liter, Varian Cair, Merk Sunlight/Setara", 1, "Buah", 85000),
        ("Detergen Cair", "Ukuran 5 Liter, Merk Soklin Detergent Matic/Setara", 1, "Bks", 85000),
        ("Pembersih Lantai", "Ukuran 4 Liter, Varian Cair, Merk Superpel/Setara", 1, "Bks", 75000),
        ("Barista Cloth", "Ukuran 30 x 60 Cm, Bahan Microfiber, Merk Standar", 5, "Roll", 20000),
        ("Tisu Wajah", "Varian 2 Ply, Isi 200 lembar, Merk Paseo/Setara", 8, "Bks", 15000),
        ("Tisu Dapur", "Kitchen Towel Isi 3 Roll, Merk Paseo Calorie Absorb/Setara", 4, "Botol", 22000),
        ("Espresso Beans", "Ukuran 1 Kg, Biji Kopi Utuh, Espresso Roast, Full Arabica", 5, "Botol", 220000),
        ("Espresso Beans", "Ukuran 1 Kg, Biji Kopi Utuh, Espresso Roast, House Blend 70/30", 7, "Box", 220000),
        ("Robusta Beans", "Ukuran 1 Kg, Biji Kopi Utuh, Espresso Roast, Full Robusta", 3, "Box", 145000),
        ("Arabica Beans", "Ukuran 500 Gr, Biji Kopi Utuh, Espresso Roast, Aceh Gayo Honey Process", 4, "Box", 325000),
        ("Arabica Beans", "Ukuran 500 Gr, Biji Kopi Utuh, Filter Roast-Semi Washed, Wanoja Kamojang Anaerobic Honey Process", 3, "Box", 325000),
        ("Arabica Beans", "Ukuran 200 Gr, Biji Kopi Utuh, Filter Roast-Honey, Bali Ulian Natural Process", 5, "Botol", 325000),
        ("Arabica Beans", "Ukuran 200 Gr, Biji Kopi Utuh, Filter Roast-Full Washed, Argopuro Anaerobic Natural Process", 3, "Buah", 325000),
        ("Arabica Beans", "Ukuran 200 Gr, Biji Kopi Utuh, Filter Roast-Natural Anaerob, Mandheling Natural Process", 2, "Buah", 325000),
        ("Arabica Beans", "Ukuran 500 Gr, Biji Kopi Utuh, Espresso Roast, Aceh Gayo Wine Process", 2, "Buah", 325000),
        ("Bubuk Kopi Instan", "Ukuran 120 Gr, Merk Nescafe Classic", 20, "Botol", 35000),
        ("Soda", "Ukuran 250 Ml (Isi 12 Pcs)", 4, "Botol", 165000),
        ("Air Botol Mineral", "Ukuran 330 Ml (Isi 24 Botol)", 4, "Botol", 55000),
        ("Teh Premium", "Isi 25 Tea Bag, Artisan Tea - Red Swangi, Merk Sila Tea House", 2, "Botol", 65000),
        ("Teh Premium", "Ukuran 100 Gram, Artisan Tea - Glorious White, Merk Sila Tea House", 1, "Botol", 65000),
        ("Teh Premium", "Ukuran 50 Gr, English Breakfast (Isi 25 Kantong), Merk Dilmah Premium Tea", 2, "Botol", 45000),
        ("Susu Fresh Milk", "Ukuran 946 ml, Rasa Plain Isi 12 Pcs, Merk Greenfield", 140, "Botol", 25000),
        ("Susu Full Cream", "Ukuran 946 ml, Rasa Plain Isi 12 Pcs, Merk Omela Foaming Milk", 100, "Botol", 24000),
        ("Susu Oat", "Ukuran 1 Liter, Varian Putih Barista Blend, Merk Oatside", 6, "Botol", 55000),
        ("Susu Cashew Original", "Ukuran 1 Liter, Rasa Cashew Milk, Merk Arrumi", 6, "Botol", 60000),
        ("Sirup Caramel", "Ukuran 750 ml, Merk Denali", 4, "Botol", 135000),
        ("Sirup Butterscotch", "Ukuran 750 ml, Merk Denali", 6, "Botol", 135000),
        ("Sirup Hazelnut", "Ukuran 750 ml, Merk Denali", 2, "Pot", 135000),
        ("Sirup Mint", "Ukuran 750 ml, Merk Denali", 1, "Pot", 135000),
        ("Sirup Green Tea", "Ukuran 750 ml, Merk Denali", 1, "Pot", 145000),
        ("Sirup Vanila", "Ukuran 750 ml, Merk Denali", 2, "Buah", 135000),
        ("Sauce Caramel", "Ukuran 2 Liter, Merk Denali", 2, "Buah", 185000),
        ("Sauce Cokelat", "Ukuran 2 Liter, Merk Denali", 2, "Buah", 185000),
        ("Gula Cair", "Ukuran 500 Gr, Merk Rose Brand/Setara", 4, "Buah", 55000),
        ("Gula Aren Cair", "Ukuran 1,3 Kg, Merk Gulare/Setara", 10, "Buah", 65000),
        ("Bubuk Coklat", "Ukuran 165 Gr, Merk Vanhouten/Setara", 2, "Buah", 95000),
        ("Bubuk Matcha", "Ukuran 800 Gr, Merk Denali", 2, "Buah", 110000),
        ("Whipped Cream", "Ukuran 1 Liter, Merk Anchor/Setara", 1, "Pot", 85000),
        ("Gula Pasir", "Ukuran 1 Kg, Merk Gulaku/Setara", 1, "Buah", 180000),
        ("Kental Manis", "Ukuran 545 Gr, Kemasan Pouch, Rasa Vanila, Merk Frisian Flag", 24, "Buah", 15000),
        ("Susu Bubuk", "Ukuran 780gr, Merk Dancow FortiGrow Full Cream", 2, "Buah", 45000),
        ("Creamer Bubuk", "Ukuran 500 Gr, Kemasan Jar (Toples), Merk Max Creamer", 2, "Buah", 55000),
        ("Chocolate Powder", "Ukuran 1 Kg, Merk Milo 3in1", 2, "Buah", 85000),
        ("Red Velvet Powder", "Ukuran 800 Gr, Merk Denali", 2, "Buah", 95000),
        ("Thai Tea Powder", "Ukuran 1000 Gr, Merk MaxFood/Setara", 2, "Buah", 75000),
        ("Es Krim Vanila", "Ukuran 8 Liter, Merk Diamond", 2, "Buah", 281000),
        ("Es Krim Coklat", "Ukuran 8 Liter, Merk Diamond", 6, "Buah", 45000),
        ("Jus Jeruk", "Ukuran 1 Liter, Merk Jungle Juice", 5, "Buah", 25000),
        ("Jus Lemon", "Ukuran 1 Liter, Merk Jungle Juice", 4, "Buah", 30000),
        ("Sprite", "Ukuran 1,5 L, Rasa Lemon Lime", 4, "Buah", 15000),
        ("Coca Cola", "Ukuran 1,5 L", 4, "Buah", 15000),
        ("Es Batu Kristal", "Es Kristal, Bungkus Plastik Ukuran 15kg", 10, "Buah", 20000),
        ("V60 Paper Filter", "Ukuran Varian 01 (1-2 cups), Isi 100 Lembar, Varian Bleached (Putih), Merk Cafec", 5, "Buah", 85000),
        ("Gelas Plastik Biasa", "Ukuran 14 Oz, Kualitas Bahan Tebal, Isi 50 pcs", 4, "Psg", 35000),
        ("Sedotan Plastik", "Bungkus Kertas, Warna Putih, Isi 500", 6, "Psg", 15000),
        ("Gelas Kertas dengan Penutup", "Ukuran 8 Oz + Tutup + Sablon Custom Logo Kemnaker--Satpel Mamuju (1000 Pcs)", 2, "Psg", 65000),
        ("Gelas Plastik Tebal (Cup Injection) dengan Penutup", "Ukuran 12 Oz (Setara Cup Fore-Coffee) + Tutup Sambung + Sablon Custom Logo Kemnaker--Satpel Mamuju (1000 Pcs)", 2, "Psg", 95000),
    ],
}

# ==========================================================================
# PAKET 2 : JUNIOR MAKE UP ARTIST (TATA KECANTIKAN)  - 160 JP
# ==========================================================================
MAKEUP = {
    "kejuruan": "Tata Kecantikan",
    "bidang": "Junior Make Up Artist",
    "judul": "Junior Make Up Artist",
    "jam": "160 JP",
    "items": [
        ("Map Kancing", "Joyko; DBG-108; Warna Bebas", 12, "Buah", 17000),
        ("Papan Jalan", "Merk Menyesuaikan; Ukuran F4", 12, "Buah", 33000),
        ("Penghapus Karet", "Faber Castel; Kecil; Putih", 12, "Buah", 5000),
        ("Spidol Whiteboard", "Snowman; Whiteboard BG-12; Hitam", 1, "Buah", 12000),
        ("Spidol Permanent", "Snowman; Permanent G-12; Hitam", 1, "Buah", 12000),
        ("Penghapus Papan Tulis", "Joyko; WE-3; Magnet", 1, "Buah", 12000),
        ("HVS F4", "SIDU; 80 GSM; 500 Lembar", 1, "Rim", 75000),
        ("HVS A4", "SIDU; 80 GSM; 500 Lembar", 1, "Rim", 65000),
        ("Tinta Printer Magenta", "Epson 003; Magenta", 1, "Botol", 156000),
        ("Tinta Printer Black", "Epson 003; Black", 1, "Botol", 156000),
        ("Tinta Printer Yellow", "Epson 003; Yellow", 1, "Botol", 156000),
        ("Tinta Printer Cyan", "Epson 003; Cyan", 1, "Botol", 156000),
        ("Handuk Cuci", "Good Morning; 30x70; Katun; Putih", 12, "Buah", 10000),
        ("Hairbando", "Mella; Bahan Handuk; Perekat", 12, "Buah", 15000),
        ("Cape Makeup", "Queen; Bahan Satin; Putih/Hitam", 12, "Buah", 20000),
        ("Kapas", "Sariayu; Kapas Wajah; 100gr", 8, "Bks", 17000),
        ("Tissue Wajah", "Nice; Tisu Kiloan; 2Ply; 700gr", 4, "Bks", 35000),
        ("Disposable Sheet", "Livi; Premium Medicare Roll; 55x50cm", 2, "Roll", 110000),
        ("Cotton Buds", "Cussons; 100 Pc", 4, "Bks", 8500),
        ("Alkohol 70%", "One Med; 300 Ml", 1, "Botol", 18500),
        ("Hand Sanitizer", "OneMed; Aseptic Gel + Dispenser; 500ml", 1, "Botol", 36000),
        ("Masker Medis", "Alkindo; Duckbill", 4, "Box", 45000),
        ("Sarung Tangan S", "Safeglove; Nitrile Powder Free; S", 2, "Box", 85000),
        ("Sarung Tangan M", "Safeglove; Nitrile Powder Free; M", 2, "Box", 85000),
        ("Penutup Kepala", "Onemed; Nurse Cap; Isi 100", 2, "Box", 64000),
        ("Brush Cleaner", "Purify Beaute; Sandalwood; 100ml", 4, "Botol", 78000),
        ("Spons Foundation", "Madame Lashes; Bentuk Mangga", 12, "Buah", 25000),
        ("Spons Bedak Padat", "Expert; Kotak", 12, "Buah", 17000),
        ("Spons Bedak Tabur", "Expert; Bulat Beludru", 12, "Buah", 17000),
        ("Milk Cleanser Mawar", "Sariayu; Mawar; 150ml", 6, "Botol", 26000),
        ("Milk Cleanser Jeruk", "Sariayu; Jeruk; 150ml", 4, "Botol", 26000),
        ("Milk Cleanser Kenanga", "Sariayu; Kenanga; 150ml", 4, "Botol", 26000),
        ("Face Toner Mawar", "Sariayu; Mawar; 150ml", 4, "Botol", 24000),
        ("Face Toner Jeruk", "Sariayu; Jeruk; 150ml", 2, "Botol", 24000),
        ("Face Toner Kenanga", "Sariayu; Kenanga; 150ml", 2, "Botol", 24000),
        ("Micellar Water", "Garnier; Bi-phase Oil; 125ml", 4, "Botol", 39000),
        ("Moisturizer Mawar", "Sariayu; Pelembab Mawar; 35ml", 4, "Botol", 17000),
        ("Moisturizer Jeruk", "Sariayu; Pelembab Jeruk; 35ml", 4, "Botol", 17000),
        ("Foundation Liquid Natural", "LT Pro; HD Perfect Image; Natural", 2, "Botol", 214000),
        ("Foundation Liquid Fair", "LT Pro; HD Perfect Image; Fair", 2, "Botol", 214000),
        ("Foundation Liquid Exotic", "LT Pro; HD Perfect Image; Exotic", 2, "Botol", 214000),
        ("Cream Foundation Yellow", "LT Pro; Smooth Corrector; Yellow Orange", 2, "Pot", 215000),
        ("Cream Foundation Chesnut", "LT Pro; Smooth Corrector; Chesnut", 2, "Pot", 215000),
        ("Cream Foundation Plum", "LT Pro; Smooth Corrector; Plum Rose", 2, "Pot", 215000),
        ("Bedak Tabur Natural", "LT Pro; Loose Powder; Natural Beige", 2, "Buah", 180000),
        ("Bedak Tabur Orche", "LT Pro; Loose Powder; Orche", 2, "Buah", 180000),
        ("Bedak Tabur Ivory", "LT Pro; Loose Powder; Ivory", 1, "Buah", 180000),
        ("Two Way Cake Y10", "La Tulipe; Refill; Y10", 4, "Buah", 57000),
        ("Two Way Cake Y20", "La Tulipe; Refill; Y20", 4, "Buah", 57000),
        ("Two Way Cake Y30", "La Tulipe; Refill; Y30", 4, "Buah", 57000),
        ("Eye Scoot", "Motex; Natural Roll; 2,5cm x 9,14m", 4, "Buah", 78000),
        ("Eye Shadow Base", "La Tulipe", 8, "Pot", 50000),
        ("Eye Shadow Rose", "Focallure; 10 Color; Withered Rose", 8, "Buah", 70000),
        ("Eye Shadow Sunflower", "Focallure; 10 Color; Sunflower Art", 8, "Buah", 70000),
        ("Blush On Scarlet", "Make Over; Scarlet Sheen (07)", 4, "Buah", 128000),
        ("Blush On Coral", "Make Over; Cruise Coral (08)", 4, "Buah", 128000),
        ("Pensil Alis", "Fanbo/Viva; Brown/Coklat", 12, "Buah", 52000),
        ("Eye Liner Pencil", "Make Over; Black Jack; 1,2g", 8, "Buah", 112000),
        ("Eyeliner Liquid", "Latulipe; Liquid Pen Waterproof; 1gr", 8, "Buah", 63000),
        ("Maskara", "Pixy; Waterproof; 7ml", 8, "Buah", 70000),
        ("Lip Liner Wine Red", "Inez; Wine Red", 4, "Buah", 67000),
        ("Lip Liner Cinnamon", "Inez; Cinnamon", 4, "Buah", 67000),
        ("Lip Stick Dusky Nude", "Implora; Lip Cream; 01 Dusky Nude", 4, "Buah", 25500),
        ("Lip Stick Brown Sugar", "Implora; Lip Cream; 12 Brown Sugar", 4, "Buah", 25500),
        ("Lip Stick Allure", "Implora; Lip Cream; 05 Allure", 4, "Buah", 25500),
        ("Lip Stick Dark Berry", "Implora; Lip Cream; 03 Dark Berry", 4, "Buah", 25500),
        ("Lip Gloss", "Pink Flash; Oh My Gloss; Bening", 4, "Buah", 25500),
        ("Bulu Mata 30 Basic", "Aiglow; 30 Basic", 12, "Psg", 9500),
        ("Bulu Mata 78 Basic", "Aiglow; 78 Basic", 12, "Psg", 9500),
        ("Bulu Mata M1", "Aiglow; M1", 12, "Psg", 9500),
        ("Bulu Mata 12(04A)", "Aiglow; 12(04A) Basic", 13, "Psg", 9500),
        ("Lem Bulu Mata", "Xpert Premium", 2, "Botol", 145000),
    ],
}

# Daftar seluruh paket
PAKET = [KOPI, MAKEUP]


def hitung_total(paket):
    """Jumlah seluruh (volume * harga_satuan) untuk satu paket."""
    return sum(vol * harga for _, _, vol, _, harga in paket["items"])
